### PR TITLE
Issue 2142 Add support for FES 2023-01

### LINKED ISSUE #2142: Add support for FES 2023-01
https://fes.flowcrypt.com/api response has changed `service` value from `enterprise-server` to `external-service`.

We need to check if this change affected android app and update code to allow both values - `enterprise-server` and `external-service`

### PR DESCRIPTION
**Pull request by DenBond7**
This PR Added support for FES 2023-01

close #2142
----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

**Comment by DenBond7** [comment]
@ioanmo226  @tomholub Please approve this PR. It's needed for a new release.

**Review by ioanmo226 — APPROVED** [review]
👍

**Comment by DenBond7** [comment]
@ioanmo226 Thank you for the fast action!

**Comment by ioanmo226** [comment]
My pleasure :-)

**Pull request merged**
