### PR TITLE
Update semaphore.yml - bigger CI machine

### PR DESCRIPTION
**Pull request by tomholub**
Trying a stronger machine to run tests

### CODE REVIEW

**Comment by tomholub** [comment]
For example this - is that the fault of the semaphore platform or our own code?

```
> Task :FlowCrypt:packageDevTestDebugAndroidTest 02:24
> Task :FlowCrypt:connectedDevTestDebugAndroidTest 10:06
Starting 47 tests on ci-test-pixel-x86-api30(AVD) - 11 10:06
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowDialogAboutBadPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 10:06
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 10:06
	Root{application-window-token=android.view.ViewRootImpl$W@34b182e, window-token=android.view.ViewRootImpl$W@34b182e, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 10:49
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowDialogWithPasswordRecommendation[ci-test-pixel-x86-api30(AVD) - 11] FAILED 10:49
  10:49
	Root{application-window-token=android.view.ViewRootImpl$W@f09aad7, window-token=android.view.ViewRootImpl$W@f09aad7, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 11:33
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testChangingQualityOfPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 11:33
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 11:33
	Root{application-window-token=android.view.ViewRootImpl$W@f12f18e, window-token=android.view.ViewRootImpl$W@f12f18e, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 12:17
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowMsgMismatchOfPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 12:17
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 12:17
	Root{application-window-token=android.view.ViewRootImpl$W@6fd2c24, window-token=android.view.ViewRootImpl$W@6fd2c24, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 13:02
com.flowcrypt.email.ui.activity.HtmlViewFromAssetsRawActivityTest > testShowTermsTitle[ci-test-pixel-x86-api30(AVD) - 11] FAILED 13:02
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 13:02
	Root{application-window-token=android.view.ViewRootImpl$W@266e954, window-token=android.view.ViewRootImpl$W@266e954, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 13:46
com.flowcrypt.email.ui.activity.ImportPublicKeyActivityTest > testImportKeyFromFile[ci-test-pixel-x86-api30(AVD) - 11] FAILED 13:46
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 13:46
	Root{application-window-token=android.view.ViewRootImpl$W@1f304c8, window-token=android.view.ViewRootImpl$W@1f304c8, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 14:43
com.flowcrypt.email.ui.activity.KeysSettingsActivityTest > testShowKeyDetailsScreen[ci-test-pixel-x86-api30(AVD) - 11] FAILED 14:43
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 14:43
	Root{application-window-token=android.view.ViewRootImpl$W@9fed80c, window-token=android.view.ViewRootImpl$W@9fed80c, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 15:29
com.flowcrypt.email.ui.activity.LegalSettingsActivityTest > testClickToTitleViewPager[ci-test-pixel-x86-api30(AVD) - 11] FAILED 15:29
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 15:29
	Root{application-window-token=android.view.ViewRootImpl$W@2cbbeb, window-token=android.view.ViewRootImpl$W@2cbbeb, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 16:16
com.flowcrypt.email.ui.activity.LegalSettingsActivityTest > testSwipeInViewPager[ci-test-pixel-x86-api30(AVD) - 11] FAILED 16:16
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 16:16
	Root{application-window-token=android.view.ViewRootImpl$W@c93461c, window-token=android.view.ViewRootImpl$W@c93461c, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 16:38
com.flowcrypt.email.ui.activity.MessageDetailsActivityTest > testTopForwardButton[ci-test-pixel-x86-api30(AVD) - 11] FAILED 16:38
	android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: messages._id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY) 16:38
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) 16:59
com.flowcrypt.email.ui.activity.MessageDetailsActivityTest > testEncryptedMsgPlaneText[ci-test-pixel-x86-api30(AVD) - 11] FAILED 16:59
	android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: messages._id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY) 16:59
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) 17:20
com.flowcrypt.email.ui.activity.MessageDetailsActivityTest > testMissingPubKey[ci-test-pixel-x86-api30(AVD) - 11] FAILED 17:20
	android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: messages._id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY) 17:20
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) 18:08
com.flowcrypt.email.ui.activity.PreviewImportPgpContactActivityTest > testLoadLotOfContacts[ci-test-pixel-x86-api30(AVD) - 11] FAILED 18:08
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 18:08
	Root{application-window-token=android.view.ViewRootImpl$W@ef6aa5b, window-token=android.view.ViewRootImpl$W@ef6aa5b, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 18:55
com.flowcrypt.email.ui.activity.PreviewImportPgpContactActivityTest > testIsDisplayedLabelAlreadyImported[ci-test-pixel-x86-api30(AVD) - 11] FAILED 18:55
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 18:55
	Root{application-window-token=android.view.ViewRootImpl$W@7c0c373, window-token=android.view.ViewRootImpl$W@7c0c373, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 19:42
com.flowcrypt.email.ui.activity.PublicKeyDetailsFragmentTest > testPubKeyDetails[ci-test-pixel-x86-api30(AVD) - 11] FAILED 19:42
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 19:42
	Root{application-window-token=android.view.ViewRootImpl$W@68f3154, window-token=android.view.ViewRootImpl$W@68f3154, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 20:32
com.flowcrypt.email.ui.activity.ShareIntentsTest > testToParamSubjectBody[ci-test-pixel-x86-api30(AVD) - 11] FAILED 20:32
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 20:32
	Root{application-window-token=android.view.ViewRootImpl$W@9e5c842, window-token=android.view.ViewRootImpl$W@9e5c842, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 21:18
com.flowcrypt.email.ui.activity.ShareIntentsTest > testSendMultipleMultiAtt[ci-test-pixel-x86-api30(AVD) - 11] FAILED 21:18
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 21:18
	Root{application-window-token=android.view.ViewRootImpl$W@7091aaf, window-token=android.view.ViewRootImpl$W@7091aaf, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 22:06
com.flowcrypt.email.ui.activity.ShareIntentsTest > testSendExtSubjectAtt[ci-test-pixel-x86-api30(AVD) - 11] FAILED 22:06
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 22:06
	Root{application-window-token=android.view.ViewRootImpl$W@9487309, window-token=android.view.ViewRootImpl$W@9487309, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 22:50
com.flowcrypt.email.ui.activity.SignInActivityTest > testUseOtherEmailProviders[ci-test-pixel-x86-api30(AVD) - 11] FAILED 22:50
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 22:50
	Root{application-window-token=android.view.ViewRootImpl$W@23c01f3, window-token=android.view.ViewRootImpl$W@23c01f3, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 23:34
com.flowcrypt.email.ui.activity.SignInActivityTest > testShowSecurityScreen[ci-test-pixel-x86-api30(AVD) - 11] FAILED 23:34
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 23:34
	Root{application-window-token=android.view.ViewRootImpl$W@a9a3bfb, window-token=android.view.ViewRootImpl$W@a9a3bfb, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 24:18
com.flowcrypt.email.ui.activity.SignInActivityTest > testUseGmail[ci-test-pixel-x86-api30(AVD) - 11] FAILED 24:18
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 24:18
	Root{application-window-token=android.view.ViewRootImpl$W@e3b14dc, window-token=android.view.ViewRootImpl$W@e3b14dc, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 25:04
com.flowcrypt.email.ui.activity.StandardReplyWithServiceInfoAndOneFileTest > testEmailMsg[ci-test-pixel-x86-api30(AVD) - 11] FAILED 25:04
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 25:04
	Root{application-window-token=android.view.ViewRootImpl$W@5becf87, window-token=android.view.ViewRootImpl$W@5becf87, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 25:48
com.flowcrypt.email.ui.activity.enterprise.CreatePrivateKeyActivityEnterpriseTest > testShowDialogWithPasswordRecommendation[ci-test-pixel-x86-api30(AVD) - 11] FAILED 25:48
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 25:48
	Root{application-window-token=android.view.ViewRootImpl$W@9375f18, window-token=android.view.ViewRootImpl$W@9375f18, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 26:31
com.flowcrypt.email.ui.activity.enterprise.CreatePrivateKeyActivityEnterpriseTest > testEmptySecondPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 26:31
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 26:31
	Root{application-window-token=android.view.ViewRootImpl$W@e90dad, window-token=android.view.ViewRootImpl$W@e90dad, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 27:18
com.flowcrypt.email.ui.activity.enterprise.SignInActivityEnterpriseTest > testErrorLogin[ci-test-pixel-x86-api30(AVD) - 11] FAILED 27:18
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 27:18
	Root{application-window-token=android.view.ViewRootImpl$W@e3ea26c, window-token=android.view.ViewRootImpl$W@e3ea26c, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 27:21
> Task :FlowCrypt:connectedDevTestDebugAndroidTest FAILED 27:21
FAILURE: Build failed with an exception. 27:21
* What went wrong: 27:21
Execution failed for task ':FlowCrypt:connectedDevTestDebugAndroidTest'. 27:21
> There were failing tests. See the report at: file:///home/semaphore/git/flowcrypt-android/FlowCrypt/build/reports/androidTests/connected/flavors/devTestDebugAndroidTest/index.html 27:21
* Try: 27:21
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 27:21
* Get more help at https://help.gradle.org 27:21
BUILD FAILED in 27m 20s 27:21
63 actionable tasks: 37 executed, 7 from cache, 19 up-to-date 27:22
 
```

**Review by seisvelas — COMMENTED** [review]
Well, it ran successfully now. I can rerun the same tests for this commit several more times in Semaphore and see if they fail. If they don't, we could assume the flakiness was a result of the CI machine being underpowered.

Let me know if that seems like a reasonable plan and I'll go ahead.

**Comment by DenBond7** [comment]
I don't see any reason to change the machine type. As for me 8 Gb of RAM it's the best choice of performance/price. Our environment uses around 6 Gb of RAM. So using a new machine type will be just expensive and a little faster(up to 25%).

**Comment by tomholub** [comment]
@DenBond7 the test initially failed with this (I later re-run it). Do you know why is that?

```
> Task :FlowCrypt:packageDevTestDebugAndroidTest 02:24
> Task :FlowCrypt:connectedDevTestDebugAndroidTest 10:06
Starting 47 tests on ci-test-pixel-x86-api30(AVD) - 11 10:06
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowDialogAboutBadPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 10:06
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 10:06
	Root{application-window-token=android.view.ViewRootImpl$W@34b182e, window-token=android.view.ViewRootImpl$W@34b182e, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 10:49
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowDialogWithPasswordRecommendation[ci-test-pixel-x86-api30(AVD) - 11] FAILED 10:49
  10:49
	Root{application-window-token=android.view.ViewRootImpl$W@f09aad7, window-token=android.view.ViewRootImpl$W@f09aad7, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 11:33
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testChangingQualityOfPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 11:33
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 11:33
	Root{application-window-token=android.view.ViewRootImpl$W@f12f18e, window-token=android.view.ViewRootImpl$W@f12f18e, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 12:17
com.flowcrypt.email.ui.activity.CreatePrivateKeyActivityTest > testShowMsgMismatchOfPassPhrase[ci-test-pixel-x86-api30(AVD) - 11] FAILED 12:17
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 12:17
	Root{application-window-token=android.view.ViewRootImpl$W@6fd2c24, window-token=android.view.ViewRootImpl$W@6fd2c24, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe 13:02
```

**Comment by DenBond7** [comment]
e1-standard-4 is enough for our purposes. If we would like to speed up tests will be better to use more machines at the same time. But I've found that it doesn't speed up tests a lot. We can receive just up to 25%. If we will migrate to use 10 machines instead of 4 we will speed up tests up to 25%. Not good. Because the most time takes restoring and building. That's why I think the current situation is the best for now. I've tried a lot of combinations. But the current option is the best for now.

I'm closing it.

**Pull request closed without merging**
