### PR TITLE
1.0.5

### PR DESCRIPTION
**Pull request by DenBond7**

### CODE REVIEW

**Comment by DenBond7** [comment]
@tomholub If we can move #894 to 1.0.6 I just need some time for testing and then we can do a release

**Comment by tomholub** [comment]
> @tomholub If we can move #894 to 1.0.6 I just need some time for testing and then we can do a release

Yes, I don't think that one needs to be done in this release, considering we have already encrypted the cache. Thanks!

**Comment by tomholub** [comment]
Please in particular test the webviews, after we forbid network requests, to see that nothing broke

**Comment by DenBond7** [comment]
Will do. I'll notify tomorrow when all things will be ready

**Comment by DenBond7** [comment]
@tomholub it's ready

**Pull request merged**
