### PR TITLE
add exempt domains to gh action

### PR DESCRIPTION
**Pull request by seisvelas**
This PR exempts certain domains from email monitoring in comments (per @DenBond7  feedback in https://github.com/FlowCrypt/flowcrypt-android/issues/1238). It also changes the name of the action from main.yml (per @Limonte's feedback in https://github.com/FlowCrypt/flowcrypt-browser/pull/3645)

As is, this exempts addresses that end in 'test' and 'example.com', but that can be modified however we like, so just let me know.

close https://github.com/FlowCrypt/flowcrypt-security/issues/128

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

**Review by DenBond7 — APPROVED** [review]

**Review by IvanPizhenko — APPROVED** [review]

**Comment by seisvelas** [comment]
If this is acceptable/merged I'll make an equivalent PR on the other public repos

**Comment by DenBond7** [comment]
test some_addres@address.com

**Comment by DenBond7** [comment]
test `test,example.com`

user@domain.test
user@example.com

**Comment by DenBond7** [comment]
user@flowcrypt.test

**Comment by seisvelas** [comment]
@DenBond7  Since this PR hasn't been merged, the new exemptions aren't in effect yet (that's why it's still alerting for those addresses)

**Comment by DenBond7** [comment]
@seisvelas Should it work with the current issue? I've tested user@domain.test, user@example.com, user@flowcrypt.test. All of them produce exceptions.

**Comment by DenBond7** [comment]
> Since this PR hasn't been merged, the new exemptions aren't in effect yet (that's why it's still alerting for those addresses)
Got it. I'm merging it now

**Comment by DenBond7** [comment]
> There were 2 email addresses found in the above comment. Please:
> 
> 1. click `three dots` -> `edit` to remove the email addresses
> 2. click `edited` in the comment header, and click on the previous revision of the comment
> 3. when viewing the old revision with an email in it, click `options` -> `delete this revision from history`

@seisvelas By the way, we can add this link in the end [Deleting sensitive information from a comment's history](https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#:~:text=an%20edit%20history.-,To%20view%20the%20details%20of%20a%20specific%20change%2C%20select%20it,To%20confirm%20deletion%2C%20click%20OK.). There are some pictures for a better understanding

**Pull request merged**
