### PR TITLE
1.1.5

### PR DESCRIPTION
**Pull request by DenBond7**

### CODE REVIEW

**Comment by tomholub** [comment]
@DenBond7 this is still marked as draft - since you said 1.0.5 is ready, is this ok to merge?

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
@DenBond7 also can you please create an internal release for every finalized PR? That would help me test it easier :+1:

**Comment by DenBond7** [comment]
> @DenBond7 this is still marked as draft - since you said 1.0.5 is ready, is this ok to merge?

Sorry, I've forgotten to switch a state. It's ready

**Comment by DenBond7** [comment]
> @DenBond7 also can you please create an internal release for every finalized PR? That would help me test it easier

No prob. Done!

**Pull request merged**
