### PR TITLE
test password protected msgs

### LINKED ISSUE #2201: Test sending password-protected messages

### PR DESCRIPTION
**Pull request by DenBond7**
This PR added a test for password-protected msgs.
Check that we create the right structure when creating a request to `"https://fes.{domain}/api/v1/message"`. 
Check that we create the right MIME message in the encrypted data.

This PR should prevent issues like #2180

close #2201 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities

### CODE REVIEW

**Comment by DenBond7** [comment]
@ioanmo226 please look at this PR. It's blocking me a little.

**Comment by tomholub** [comment]
@ioanmo226 in case you overlooked this

**Comment by ioanmo226** [comment]
Ohh, sorry.
I missed this message.
My outlook message forwarding sometimes get reset and I don't get email notification to my primary email.

**Review by ioanmo226 — APPROVED** [review]
👍

**Comment by tomholub** [comment]
Is that, from GitHub notification email? You could consider changing that email in GitHub settings (I think notification email can be set independently?)

**Comment by ioanmo226** [comment]
Yeah, I think so.
Will set notificaiton email to my primary email.

**Pull request merged**
