### PR TITLE
issue 1251 add keyCacheWipe and fix key_mismatch

### PR DESCRIPTION
**Pull request by tomholub**
This PR adds a `keyCacheWipe` endpoint (zero input, zero output) that wipes cache of decrypted keys.

Also fixes key_mismatch error when missing pass phrase.

issue #1251 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later (@DenBond7 please do in issue #1251 )

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

**Comment by tomholub** [comment]
discussion here https://github.com/FlowCrypt/flowcrypt-android/issues/1251#issuecomment-854404034

**Review by DenBond7 — APPROVED** [review]

**Comment by DenBond7** [comment]
@tomholub Thank you! Merged.

**Comment by DenBond7** [comment]
@tomholub Please let me clarify. Should it work automatically or I need to do some API request to wipe the cache?

**Comment by tomholub** [comment]
A new endpoint called `keyCacheWipe` was added - you have to call that to wipe the cache.

**Pull request merged**
