### PR TITLE
Improved the decrypting MIME message process

### LINKED ISSUE #2523: Improve decrypt MIME message process
- Send a secure email from Android Flowcrypt application to an external address mail
- Send a reply from the FES with an attachment of approximately 4MB.
- Try to open the email from [replies@flowcrypt.com](mailto:replies@flowcrypt.com) in the Android Flowrcrypt application
- Should see the error 
- After a while it changes in an infinite loop load.

### PR DESCRIPTION
**Pull request by DenBond7**
This PR Improved the decrypting MIME message process

close #2523

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated
--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities

### CODE REVIEW

**Review by sosnovsky — COMMENTED** [review]
When trying to open `flowcrypt-browser #5248 pgp/mime with inline image attachment` message in `flowcrypt.compatibility` account I get such error:

**Comment by DenBond7** [comment]
Did you install a fresh version or upgraded an existing?

**Comment by sosnovsky** [comment]
> Did you install a fresh version or upgraded an existing?

I had previously installed version from `master` branch, which was then updated to this PR.
So probably such issue can happen for users who will update from older versions?

**Comment by DenBond7** [comment]
> > Did you install a fresh version or upgraded an existing?
> 
> I had previously installed version from `master` branch, which was then updated to this PR. So probably such issue can happen for users who will update from older versions?

Nope. An update will erase the messages cache.

You can reproduce the same behavior. Just need to increase the app version. 

https://github.com/FlowCrypt/flowcrypt-android/blob/master/ext.gradle.kts

Please use

extra["appVersionCode"] = 149
extra["appVersionName"] = "1.4.9"

**Comment by sosnovsky** [comment]
> You can reproduce the same behavior. Just need to increase the app version.
> 
> https://github.com/FlowCrypt/flowcrypt-android/blob/master/ext.gradle.kts
> 
> Please use
> 
> extra["appVersionCode"] = 149 extra["appVersionName"] = "1.4.9"

Yeah, it works well after this change, thanks for the tip!

**Review by sosnovsky — APPROVED** [review]
Works great 👍

**Comment by sosnovsky** [comment]
@DenBond7 I don't have permissions to merge PRs in this repository, can you please merge it

Screenshot 2023-12-12 at 23 38 13

**Pull request merged**
