### PR TITLE
issue #1074 Introduce project specific code formatting settings

### PR DESCRIPTION
**Pull request by IvanPizhenko**
This PR formatting settings as described by the @DenBond7 right into the IntelliJ project.

### CODE REVIEW

**Comment by IvanPizhenko** [comment]
@DenBond7 Semaphore fails, likely due to some timeout
```
com.flowcrypt.email.ui.activity.ImportPrivateKeyActivityFromSettingsTest > testImportKeyFromBackup[ci-test-pixel-x86-api30(AVD) - 11] FAILED 24:19
        java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root: 24:19
        Root{application-window-token=android.view.ViewRootImpl$W@4804303, window-token=android.view.ViewRootImpl$W@4804303, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
```
Please take a look.
I have already restarted semaphore few times and all times it failed on the one of the "Instrumentation tests" - each time on different one. Sometimes few instrumentation tests stopped in the middle. Maybe something can be done about this? Like increasing some timeouts.

**Comment by IvanPizhenko** [comment]
trying to re-run once again...

**Comment by IvanPizhenko** [comment]
Increased test execution time limit by 10 minutes

**Review by tomholub — APPROVED** [review]
I'll merge this. If something is wrong, @DenBond7 let me know. I'll also rely on your code reviews in the future before merging. Thanks!

**Comment by DenBond7** [comment]
@tomholub 
> If something is wrong, @DenBond7 let me know.

All looks good. @IvanPizhenko Thanks for a good job.

**Pull request merged**
