### PR TITLE
1.1.1

### PR DESCRIPTION
**Pull request by DenBond7**
- [x] check tests

### CODE REVIEW

**Comment by DenBond7** [comment]
@tomholub 
it's ready

**Review by tomholub — APPROVED** [review]
Looks good, I updated comments here https://github.com/FlowCrypt/flowcrypt-android/pull/938/commits/3b391e275488ef266239467f019f5ea113691fac - please later confirm I updated them correctly

**Comment by DenBond7** [comment]
> Looks good, I updated comments here [3b391e2](https://github.com/FlowCrypt/flowcrypt-android/commit/3b391e275488ef266239467f019f5ea113691fac) - please later confirm I updated them correctly

@tomholub Your changes look correct

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
You can make another PR from the master like 1.1.1-lint-fix, that will be the easiest

**Pull request merged**
