### PR TITLE
Update build.gradle to support dependabot

### LINKED ISSUE #1776: Update build.gradle to support dependabot

### PR DESCRIPTION
**Pull request by DenBond7**
This PR Updated `build.gradle` to support `dependabot`

close #1776 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

**Comment by DenBond7** [comment]
@tomholub Please look at Snyk. I don't have an access

**Comment by tomholub** [comment]
It can newly understand the file, and found a vulnerability in one of the deps

image

**Comment by DenBond7** [comment]
@tomholub  We use 
https://github.com/FlowCrypt/flowcrypt-android/blob/076b1af2a554b423a4a4424dd01c2dd033a2a7d3/FlowCrypt/build.gradle#L365

that uses a newer version 

```
+--- org.jetbrains.kotlin:kotlin-reflect:1.6.21
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 (*)
```

Gradle automatically uses the freshest version of existing dependencies. It seems Snyk can't recognize it.

image

I almost didn't do any changes here. Just deleted links and used direct names. We need to merge it to be able to update left dependencies via `dependabot`. Need to update all dependencies and check the final result.

**Review by IvanPizhenko — APPROVED** [review]

**Comment by IvanPizhenko** [comment]
@DenBond7 @tomholub Some Snyk issue, please have a look

**Pull request merged**
